const events = [
 {id:'blender',category:'传统建模',type:'软件更新',status:'升温',date:'2024-07-16',title:'Blender 4.2 LTS：实时渲染迎来一次大更新',summary:'EEVEE 重写，带来新的全局光照、位移与景深表现。',background:'EEVEE 是 Blender 的实时渲染引擎，适合快速预览、动画和风格化创作。4.2 LTS 重写了引擎，让艺术家可以在更接近最终效果的画面里工作。LTS 表示长期支持版本。',signal:'正式发布与长期支持机制，是观察专业用户迁移和工作流测试的切入点。当前“升温”标签仅用于界面演示。',meaning:'一句话：Blender 把实时预览的画质和稳定性整体往前推了一步，让更多创作者可以在接近最终效果的画面里直接制作。',difference:'以前：EEVEE 更偏快速预览，复杂光照和置换效果常需要切到 Cycles 或离线渲染；现在：EEVEE Next 重写了光照、阴影、置换和景深等核心能力，并以 4.2 LTS 形式长期维护。',industryImpact:'对 3D 行业：建模、材质和动画的迭代反馈更快，实时风格化、虚拟制作和资产展示的成本下降，但不同硬件上的效果仍需实测。',tripoImpact:'对 Tripo：生成模型进入 Blender 后，可以更快完成材质、灯光和镜头预览；导出资产的真实生产价值会更依赖 Blender 4.2 的兼容性与渲染表现。',images:[['EEVEE Next 官方示意','https://developer.blender.org/docs/release_notes/4.2/'],['Blender 4.2 发布页','https://www.blender.org/download/releases/4-2/']],evidence:[['官方发布页 · 4.2 LTS','页面中的“Blender 4.2 LTS”与版本定位，确认这是长期支持版本。'],['开发者文档 · EEVEE Next','在文档内查找 “EEVEE Next” 小节，重点看 Global Illumination、Shadow、Light Linking、Depth of Field。'],['开发者文档 · Geometry Nodes','在页面内查找 “Repeat Zone” 或 “Geometry Nodes”，核对程序化建模相关变化。']],sources:[['Blender 官方','https://www.blender.org/download/releases/4-2/'],['开发者文档（EEVEE Next）','https://developer.blender.org/docs/release_notes/4.2/']],tags:['Blender','EEVEE','实时渲染']},
 {id:'gaussian',category:'学术研究',type:'论文 / 代码',status:'专业关注',date:'2023-08-08',title:'3D Gaussian Splatting，让实景重建实时可看',summary:'用三维高斯表示场景，在新视角画质与渲染速度之间找到新路径。',background:'这项 SIGGRAPH 2023 研究以一组可优化的三维高斯表示场景。相较传统网格，它更侧重从照片重建可观看的场景；可编辑资产、几何精度与动态场景仍是需要分别评估的问题。',signal:'论文、官方实现与后续工具是不同的证据层。技术价值可以从方法和实验理解，实际关注增长仍需持续采样。',sources:[['论文原文','https://arxiv.org/abs/2308.04079'],['GitHub','https://github.com/graphdeco-inria/gaussian-splatting']],tags:['Gaussian Splatting','场景重建','实时渲染']},
 {id:'trellis',category:'AI 3D',type:'研究 / 开源',status:'升温',date:'2024-12-05',title:'TRELLIS：一张图，生成多种形式的 3D 资产',summary:'结构化潜在表示，让同一生成流程输出网格、辐射场或三维高斯。',background:'TRELLIS 是微软公开的3D生成研究。其核心是结构化潜在表示（SLAT），将形状与外观信息编码在统一表示中，再解码为不同3D格式。生成结果仍需按目标生产流程检查。',signal:'可阅读的论文、公开代码和可运行示例让研究能被开发者测试。演示排序不代表当前 GitHub 热度。',sources:[['GitHub','https://github.com/microsoft/TRELLIS'],['论文原文','https://arxiv.org/abs/2412.01506']],tags:['图生3D','开源','TRELLIS']},
 {id:'godot',category:'引擎与交互',type:'软件更新',status:'新发现',date:'2024-08-15',title:'Godot 4.3 发布，开源游戏引擎继续完善 3D 工作流',summary:'渲染、物理和编辑器体验更新，为独立开发提供更多选择。',background:'Godot 是开源游戏引擎。评估引擎更新时，需要结合渲染能力、平台兼容性、资产导入和现有项目升级成本，不应只看新功能数量。',signal:'版本公告说明发生了什么；实际使用体验需要结合迁移报告和开发者测试。',sources:[['版本公告','https://godotengine.org/releases/4.3/'],['GitHub','https://github.com/godotengine/godot/releases/tag/4.3-stable']],tags:['Godot','游戏开发','开源']},
 {id:'openusd',category:'行业动态',type:'标准 / 生态',status:'专业关注',date:'2023-08-01',title:'OpenUSD 联盟成立，推动 3D 内容在软件间流转',summary:'多家企业共同推进通用场景描述，减少复杂3D管线中的互通障碍。',background:'USD 不只是模型文件格式，还可以描述大型场景、层级、材质绑定和资产组合。OpenUSD 联盟推动相关标准建设，帮助不同软件在场景数据上协作。',signal:'行业标准的价值体现在工具支持和真实管线采用。联盟成立是历史事件，不能自动当作今天的热点。',sources:[['官方公告','https://www.apple.com/newsroom/2023/08/pixar-adobe-apple-autodesk-and-nvidia-form-alliance-for-openusd/'],['AOUSD','https://aousd.org/']],tags:['OpenUSD','资产互通','生产管线']},
 {id:'instantmesh',category:'AI 3D',type:'论文 / 开源',status:'专业关注',date:'2024-04-09',title:'InstantMesh：从单张图片重建 3D 网格',summary:'结合多视图扩散与稀疏视图重建，把图像转成可导出的网格。',background:'单张图像没有展示物体背面，因此重建会结合输入和模型先验推断不可见部分。InstantMesh 通过生成多视图再重建网格完成转换，几何正确性仍需检查。',signal:'公开代码和方法说明可用于复现学习；生成速度、效果与硬件配置需要在相同条件下比较。',sources:[['论文原文','https://arxiv.org/abs/2404.07191'],['GitHub','https://github.com/TencentARC/InstantMesh']],tags:['图生3D','网格重建','开源']},
 {id:'geometry',category:'传统建模',type:'工作流 / 工具',status:'专业关注',date:'2023-11-14',title:'Blender 几何节点加入 Repeat Zone，程序化建模更灵活',summary:'在节点内部重复执行操作，让迭代生成与几何处理更直接。',background:'几何节点通过节点连接定义建模流程。Repeat Zone 可以在同一节点树内重复执行指定操作，适合逐步变形、迭代构建等程序化任务。',signal:'这是 Blender 4.0 的历史功能示例，用于展示工作流类事件；当前不声称它正在突然走红。',sources:[['发布说明','https://developer.blender.org/docs/release_notes/4.0/geometry_nodes/'],['使用手册','https://docs.blender.org/manual/en/latest/modeling/geometry_nodes/utilities/repeat_zone.html']],tags:['Blender','程序化建模','几何节点']},
 {id:'three',category:'引擎与交互',type:'开发工具',status:'专业关注',date:null,title:'Three.js 的 WebGPU 路线：浏览器 3D 的新工具链',summary:'WebGPURenderer 与节点材质，连接网页交互和现代图形能力。',background:'WebGPU 是面向现代 GPU 的 Web 图形与计算接口。Three.js 的相关渲染器帮助开发者构建实时3D应用，落地时仍需检查浏览器支持与功能兼容。',signal:'这是一条持续观察话题。只有出现新版本、采用案例或讨论增长后，才能据实判断是否升温。',sources:[['Three.js 文档','https://threejs.org/docs/'],['GitHub','https://github.com/mrdoob/three.js']],tags:['Three.js','WebGPU','实时渲染']},
 {id:'bim',category:'行业应用',type:'开源 / 建筑',status:'专业关注',date:null,title:'Bonsai：在 Blender 中完成开放 BIM 工作流',summary:'围绕 IFC 数据开展建筑建模、检查与协作，让设计连接工程信息。',background:'BIM 同时包含三维几何与建筑信息。Bonsai 基于 IfcOpenShell，与 Blender 集成，重点是编辑和管理 IFC 数据，而不只是生成建筑外观。',signal:'常青项目作为行业应用样例。真实雷达会追踪新版本、案例和社区动向，而不是每天重复推荐项目主页。',sources:[['Bonsai 官网','https://bonsaibim.org/'],['GitHub','https://github.com/IfcOpenShell/IfcOpenShell']],tags:['BIM','建筑','Blender']},
 {id:'slang',category:'图形与渲染',type:'开发工具 / 开源',status:'新发现',date:null,title:'Slang：把着色器开发连接到多种 GPU 平台',summary:'以模块化与跨平台编译支持更复杂的渲染和计算项目。',background:'着色器是 GPU 上运行的程序。Slang 是面向图形与计算开发的语言及编译工具链，提供模块化等能力；具体平台支持应以官方文档为准。',signal:'项目本身不是每日新闻。原型展示其阅读方式，之后需绑定具体发布或专业讨论才能进入当天热点。',sources:[['官方文档','https://shader-slang.org/'],['GitHub','https://github.com/shader-slang/slang']],tags:['Shader','GPU','实时渲染']}
];

const historicalCases = [
 {id:'case-trellis',use:'资产生成',title:'用 TRELLIS 把一张图变成多种 3D 表达',desc:'同一个图像输入，输出网格、辐射场和 Gaussian 表示，适合比较不同资产形态。',tools:'TRELLIS · Python · CUDA',source:['GitHub','https://github.com/microsoft/TRELLIS'],image:'https://raw.githubusercontent.com/microsoft/TRELLIS/main/assets/teaser.png'},
 {id:'case-gaussian',use:'场景重建',title:'用 3D Gaussian Splatting 重建可浏览的真实空间',desc:'从多张照片重建场景，再在新视角中实时浏览，展示扫描到体验的完整路径。',tools:'Gaussian Splatting · COLMAP · WebGL',source:['论文与代码','https://github.com/graphdeco-inria/gaussian-splatting'],image:'https://raw.githubusercontent.com/graphdeco-inria/gaussian-splatting/main/assets/teaser.png'},
 {id:'case-instant',use:'图像转模型',title:'InstantMesh：单张图片生成可导出的 3D 网格',desc:'多视图生成加稀疏视图重建，把一张参考图推进到可检查的网格结果。',tools:'InstantMesh · Diffusion · Mesh',source:['GitHub','https://github.com/TencentARC/InstantMesh'],image:'https://raw.githubusercontent.com/TencentARC/InstantMesh/main/assets/teaser.png'},
 {id:'case-blender',use:'自动化工作流',title:'让 AI 写 Blender 脚本，批量生成一组场景',desc:'把自然语言拆成脚本、对象、材质和镜头，让 AI 参与传统 DCC 的重复工作。',tools:'Blender Python · AI Coding',source:['Blender API','https://docs.blender.org/api/current/'],image:null},
 {id:'case-web3d',use:'交互体验',title:'把 3D 资产放进可交互的网页体验',desc:'模型不止用于展示，也可以成为网页、小游戏或产品配置器中的可操作对象。',tools:'Three.js · WebGPU · glTF',source:['Three.js','https://threejs.org/docs/'],image:null},
 {id:'case-modular',use:'游戏生产',title:'把一栋房子拆成可复用的游戏资产套件',desc:'从单个建筑概念出发，拆分模块、批量生成，再放入引擎验证复用效果。',tools:'Blender · Unity · Modular Kit',source:['案例参考','https://www.youtube.com/results?search_query=AI+3D+modular+game+assets'],image:null}
];
const cases = socialCases;
const categories=['全部','传统建模','AI 3D','学术研究','引擎与交互','图形与渲染','行业应用','行业动态'];
const $=s=>document.querySelector(s);
let category='全部',query='',sort='rank',view='today',saved=new Set(),activeId=null,toastTimer,caseUse='全部',caseFormat='全部',caseQuery='';
try{const stored=JSON.parse(localStorage.getItem('3d-radar-saved')||'[]');if(Array.isArray(stored))saved=new Set(stored.filter(id=>events.some(e=>e.id===id)));}catch{}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=e=>`<span class="status ${e.status==='升温'?'rising':e.status==='新发现'?'new':'professional'}">${e.status}</span>`;
const sources=e=>e.sources.map(([name,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer" aria-label="阅读${esc(name)}原始来源（新标签页）">${esc(name)} ↗</a>`).join('');
const saveButton=e=>`<button class="save" data-save="${e.id}" aria-label="${saved.has(e.id)?'取消收藏':'收藏'}：${esc(e.title)}" aria-pressed="${saved.has(e.id)}" title="${saved.has(e.id)?'取消收藏':'收藏事件'}">${saved.has(e.id)?'★':'☆'}</button>`;
function render(){
 $('#featured-section').hidden=view!=='today';$('#intro').hidden=view!=='today';
 $('#cases').hidden=!['today','cases'].includes(view);
 $('#feed-section').hidden=view==='cases';
 $('.prototype-note').hidden=view==='cases';
 const uses=['全部',...new Set(cases.map(c=>c.use))]; $('#case-filters').innerHTML=uses.map(u=>`<button data-case-use="${u}" class="${caseUse===u?'active':''}">${u}</button>`).join('');
 const formats=['全部',...new Set(cases.map(c=>c.format))]; $('#case-formats').innerHTML=formats.map(f=>`<button data-case-format="${f}" class="${caseFormat===f?'active':''}">${f}</button>`).join('');
 const shownCases=CaseUI.filterCases(cases,{use:caseUse,format:caseFormat,query:caseQuery});
 $('#case-count').textContent=`${shownCases.length} 条真实作品 · 2026-09-10 收录`;
 $('#case-empty').hidden=shownCases.length>0;
 $('#case-grid').innerHTML=shownCases.map(CaseUI.caseCard).join('');
 $('#featured').innerHTML=events.slice(0,3).map((e,i)=>`<article class="feature"><div class="feature-top"><span class="feature-num">0${i+1}</span>${badge(e)}</div><div class="feature-category">${e.category} / ${e.type}</div><h3><button class="title-button" data-event="${e.id}">${e.title}</button></h3><p>${e.summary}</p><div class="source-links">${sources(e)}</div></article>`).join('');
 let list=events.filter(e=>(category==='全部'||e.category===category)&&(view!=='saved'||saved.has(e.id))&&(!query||[e.title,e.summary,...e.tags,e.category,e.type].join(' ').toLowerCase().includes(query.toLowerCase())));
 if(sort==='recent')list.sort((a,b)=>(b.date||'').localeCompare(a.date||''));if(sort==='sources')list.sort((a,b)=>b.sources.length-a.sources.length);
 $('#feed-title').innerHTML=`${view==='saved'?'我的收藏':view==='explore'?'全部事件':'热点速览'} <span id="result-count">${list.length} 条事件</span>`;
 $('#categories').innerHTML=categories.map(c=>`<button data-category="${c}" class="${category===c?'active':''}" aria-pressed="${category===c}">${c}</button>`).join('');
 $('#event-list').innerHTML=list.map(e=>`<article class="event"><span class="event-rank">${String(events.indexOf(e)+1).padStart(2,'0')}</span><div><div class="event-meta">${badge(e)}<span>${e.category}</span><span>·</span><span>${e.type}</span></div><h3><button class="title-button" data-event="${e.id}">${e.title}</button></h3><p>${e.summary}</p><div class="event-bottom"><div class="source-links">${sources(e)}</div><span class="source-count">${e.sources.length} 个来源</span></div></div>${saveButton(e)}</article>`).join('');
 $('#empty').hidden=!!list.length;$('#end-note').hidden=!list.length;$('#saved-count').textContent=saved.size;
 $('#active-filter').hidden=!query&&category==='全部';$('#active-filter').innerHTML=`${query?'搜索：'+esc(query):''}${category!=='全部'?' · '+category:''}<button id="clear-filter">清除筛选 ×</button>`;
 document.querySelectorAll('[data-view]').forEach(a=>a.classList.toggle('active',a.dataset.view===view));
}
function openCase(id){const c=cases.find(x=>x.id===id);if(!c)return;$('#case-body').innerHTML=CaseUI.caseDetail(c);if(!$('#case-detail').open)$('#case-detail').showModal();}
function openDetail(id){const e=events.find(e=>e.id===id);if(!e)return;activeId=id;const meaning=e.meaning||`一句话：${e.summary}`;const difference=e.difference||'目前资料未提供明确的版本对比，需继续核对原始发布说明与此前版本。';const industryImpact=e.industryImpact||`对 3D 行业：${e.signal}`;const tripoImpact=e.tripoImpact||'对 Tripo 的影响：需要结合资产生成、导出格式、渲染或工作流的实际测试后判断，当前不下结论。';const evidence=e.evidence||e.sources.map(([name])=>[`${name} · 待读定位`,'当前仅确认来源入口，尚未完成段落级定位；打开原文后应核对标题、发布日期和关键变更。']);const media=e.images||e.sources.map(([name,url])=>[name,url]);$('#detail-body').innerHTML=`<div class="event-meta">${badge(e)}<span>${e.category} / ${e.type}</span></div><h2>${e.title}</h2><div class="detail-meta">${e.date?'原始事件日期：'+e.date:'持续观察话题 · 无单一发布日期'} · 历史样例</div><p class="detail-intro">${e.summary}</p><h3>发生了什么 / 背景知识</h3><p>${e.background}</p><h3>一句话判断</h3><p>${meaning}</p><div class="judgement-grid"><div><b>和之前有什么不同</b><p>${difference}</p></div><div><b>对 3D 行业的影响</b><p>${industryImpact}</p></div><div><b>对 Tripo 的影响</b><p>${tripoImpact}</p></div></div><h3>图片与案例佐证</h3><div class="evidence-gallery">${media.map(([label,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer"><div class="gallery-placeholder">3D</div><span>${label}<small>打开来源页面查看原图</small></span></a>`).join('')}</div><h3>来源资料整理</h3><div class="evidence excerpts">${evidence.map(([title,text])=>`<div><b>${title}</b><p>${text}</p></div>`).join('')}</div><h3>回到原始来源 <span class="detail-meta">${e.sources.length} 个链接</span></h3><div class="evidence">${e.sources.map(([name,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer"><span>${name}<small>${new URL(url).hostname}</small></span><span>打开并按上方定位阅读 ↗</span></a>`).join('')}</div><p class="detail-note">演示说明：本页没有实时热度数据。未来将根据多次采集快照展示增长与传播证据；没有数据时保持空缺。</p><button class="solid-button detail-save" data-save="${id}">${saved.has(id)?'已收藏 · 点击取消':'收藏这条事件'}</button>`;if(!$('#detail').open)$('#detail').showModal();}
function toggleSave(id){saved.has(id)?saved.delete(id):saved.add(id);let persisted=true;try{localStorage.setItem('3d-radar-saved',JSON.stringify([...saved]));}catch{persisted=false;}render();if($('#detail').open)openDetail(activeId);$('#toast').textContent=persisted?(saved.has(id)?'已收藏，稍后可以继续阅读':'已取消收藏'):'当前浏览器无法保存，收藏仅在本次页面内有效';$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2200);}
function reset(){category='全部';query='';$('#search').value='';render();}
document.addEventListener('click',event=>{const el=event.target.closest('[data-category],[data-case-use],[data-case-format],[data-case],[data-event],[data-save],[data-topic]');if(el?.dataset.category){category=el.dataset.category;render();}if(el?.dataset.caseUse){caseUse=el.dataset.caseUse;render();}if(el?.dataset.caseFormat){caseFormat=el.dataset.caseFormat;render();}if(el?.dataset.case)openCase(el.dataset.case);if(el?.dataset.event)openDetail(el.dataset.event);if(el?.dataset.save)toggleSave(el.dataset.save);if(el?.dataset.topic){view='explore';history.replaceState(null,'','#explore');query=el.dataset.topic;category='全部';$('#search').value=query;render();$('#feed-section').scrollIntoView();}if(event.target.id==='clear-filter')reset();});
$('#case-search').addEventListener('input',e=>{caseQuery=e.target.value;render();});
$('#search').addEventListener('input',e=>{query=e.target.value;render();});$('#sort').addEventListener('change',e=>{sort=e.target.value;render();});$('#reset').addEventListener('click',reset);
$('#about').onclick=()=>$('#info').showModal();$('#close-case').onclick=()=>$('#case-detail').close();$('#close-detail').onclick=()=>$('#detail').close();$('#close-info').onclick=()=>$('#info').close();
for(const dialog of document.querySelectorAll('dialog')){dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});dialog.addEventListener('close',()=>document.body.style.overflow='');dialog.addEventListener('toggle',()=>{if(dialog.open)document.body.style.overflow='hidden';});}
function route(){const target=location.hash.slice(1);view=['today','explore','saved','cases'].includes(target)?target:'today';reset();window.scrollTo(0,0);}window.addEventListener('hashchange',route);
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();$('#search').focus();}});
$('#topic-links').innerHTML=['Blender','Gaussian Splatting','程序化建模','OpenUSD','WebGPU','图生3D'].map(t=>`<button data-topic="${t}">${t}<span>↗</span></button>`).join('');route();
