const CaseUI=(()=>{
 const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const safeUrl=url=>{try{const u=new URL(url);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'#';}catch{return '#';}};
 const cover=c=>c.image?'<img src="'+escape(c.image)+'" alt="'+escape(c.title)+' · 作者原帖封面" loading="lazy">':'<div class="social-cover-empty"><b>'+escape(c.platform)+'</b><small>打开原帖查看作品</small></div>';
 const link=(url,label)=>'<a href="'+escape(safeUrl(url))+'" target="_blank" rel="noopener noreferrer">'+escape(label)+' ↗</a>';
 function filterCases(items,{use='全部',format='全部',query=''}={}){
  const term=query.trim().toLowerCase();
  return items.filter(c=>(use==='全部'||c.use===use)&&(format==='全部'||c.format===format)&&(!term||[c.title,c.desc,c.author,c.platform,c.tools,c.combination].join(' ').toLowerCase().includes(term)));
 }
 function caseCard(c){return '<article class="case-card social-card"><button class="social-cover" data-case="'+escape(c.id)+'" aria-label="查看案例：'+escape(c.title)+'">'+cover(c)+'<span>'+escape(c.format)+'</span></button><div class="case-copy"><div class="social-byline">'+escape(c.platform)+' · '+escape(c.author)+'</div><h3><button class="title-button" data-case="'+escape(c.id)+'">'+escape(c.title)+'</button></h3><p>'+escape(c.desc)+'</p><div class="social-combo">'+escape(c.combination)+'</div><p class="social-learning"><b>可以借鉴</b> '+escape(c.adaptation)+'</p><div class="social-date">发布：'+escape(c.publishedLabel)+'</div><div class="social-actions">'+link(c.url,'看原帖')+'<button data-case="'+escape(c.id)+'">看创作拆解 →</button></div></div></article>';}
 function caseDetail(c){return '<div class="social-detail"><div class="social-byline">'+escape(c.platform)+' · '+escape(c.author)+'</div><h2>'+escape(c.title)+'</h2><p class="detail-intro">'+escape(c.desc)+'</p><div class="social-meta">'+escape(c.nature)+'<br>原始发布：'+escape(c.publishedLabel)+'<br>收录：'+escape(c.collectedAt)+' · '+escape(c.checkLabel)+'</div><a class="social-detail-cover" href="'+escape(safeUrl(c.url))+'" target="_blank" rel="noopener noreferrer">'+cover(c)+'<span>查看作者原作 ↗</span></a><p class="social-caption">'+(c.image?'作者原帖封面 / 动图首帧；作品版权归原作者。':'公开版不转载未获授权的图片。')+'点击查看原视频或完整图文。</p><h3>这个作品结合了什么</h3><p class="social-combo">'+escape(c.combination)+'</p><h3>作者公开的方法</h3><p>'+escape(c.method)+'</p><p><b>工具依据：</b>'+escape(c.tools)+'</p><div class="social-warning"><b>尚未核实 / 使用边界</b><p>'+escape(c.unknown)+'</p></div><h3>社媒表达与可借鉴点 <small>编辑建议，不是作者原话</small></h3><p>'+escape(c.hook)+'</p><div class="social-ideas"><section><b>如果我们做视频</b><p>'+escape(c.videoIdea)+'</p></section><section><b>如果我们做图文 Post</b><p>'+escape(c.postIdea)+'</p></section></div><h3>从这个案例出发</h3><p>'+escape(c.adaptation)+'</p><h3>核实依据与原帖定位</h3><p>'+escape(c.evidence)+'</p><div class="social-actions">'+link(c.url,'打开原帖')+(c.chapters||[]).map(([label,seconds])=>link(c.url+'&t='+seconds+'s',label)).join('')+'</div><p class="social-caption">原帖核对时间：'+escape(c.checkedAt)+'。未复现整个制作流程；不以单次浏览量判断爆款。收录仅供学习参考，不代表授权转载、素材复用或品牌合作。</p></div>';}
 return {filterCases,caseCard,caseDetail};
})();
if(typeof module!=='undefined')module.exports=CaseUI;
