const socialCases = [
  {
    "id": "DJkn1IUEfJI",
    "author": "TwinPlayz",
    "platform": "YouTube",
    "format": "制作过程",
    "use": "AI 工作流",
    "title": "从生成资产到 Roblox：把“能用在哪”放进封面",
    "desc": "作者发布 AI 建模教程，封面把绿色箱体在生成端与 Roblox Studio 中的状态并排展示，让用途比工具名称更直观。",
    "combination": "AI 3D × 游戏资产 × 前后对照",
    "tools": "Tripo；Roblox Studio 出现在原视频封面",
    "method": "原简介明确提到 Tripo Smart Mesh P2.0、游戏角色创作挑战；封面可见 Roblox Studio 与箱体资产。",
    "evidence": "原视频标题、作者、简介及封面；未逐帧核对 10 分钟全片。",
    "unknown": "完整导入设置、拓扑质量、实际用时尚未核实；不能据封面断言达到生产标准。简介含邀请码及折扣推广。",
    "hook": "编辑观察：用同一个资产连接“生成结果”和“最终用途”，观众容易理解为什么要看。",
    "videoIdea": "先展示自有资产在游戏里的效果，再倒回参考图、生成、检查和导入；最后回到可玩的场景。",
    "postIdea": "四张图：最终用途 → 输入参考 → 生成结果 → 进引擎后的修改点。",
    "adaptation": "选一件游戏道具做完整去向展示，而不是再拍一次网站点击教程；必须展示自己实际完成的导入结果。",
    "checkLabel": "简介与封面已核实",
    "nature": "创作者教程 · 含推广信息",
    "url": "https://www.youtube.com/watch?v=DJkn1IUEfJI",
    "originalTitle": "How To Make 3D Models Using AI",
    "originalPublishedAt": "2026-09-08T10:48:00-07:00",
    "publishedLabel": "2026-09-09 01:48（北京时间）",
    "image": "media/social/DJkn1IUEfJI.jpg",
    "imageSource": "https://i.ytimg.com/vi/DJkn1IUEfJI/maxresdefault.jpg",
    "snapshot": "research/2026-09-10/social/e44e3a674a2e1710f2a6747b52fda7ac.json",
    "checkedAt": "2026-09-10T08:22:37+00:00",
    "collectedAt": "2026-09-10",
    "videoId": "DJkn1IUEfJI"
  },
  {
    "id": "Db8XbcuprRD",
    "author": "MANIKANDAN RAJENDRAN · @manicgvfx",
    "platform": "Instagram",
    "format": "短视频",
    "use": "实拍与特效",
    "publishedLabel": "2026-08-12（平台日期，未核实时区）",
    "title": "街头人物腾空：成片与角色控制结构一起展示",
    "desc": "原帖封面是车流中的人物腾空镜头；视频抽查可见简化彩色角色控制结构，把动作效果与幕后制作连在一起。",
    "combination": "街头影像 × CG 人物动作 × 幕后拆解",
    "tools": "Blender（作者标签确认）",
    "method": "作者将作品标记为个人 Blender 项目 breakdown。原帖可见成片封面及角色控制结构片段。",
    "evidence": "原帖正文、发布时间、封面与实际播放画面抽查；评论中的插件猜测不作为工具证据。",
    "unknown": "未核实具体绑定/动力学插件、渲染器、素材拍摄方式与全片分镜；没有证据证明使用 AI。",
    "hook": "编辑观察：日常街景里出现不合常理的动作，再展示结构，能自然引出“怎么做的”。",
    "videoIdea": "用自己拍摄的安全空场景，加入原创角色或道具的夸张动作，再切换到视口对照；不实际模仿危险动作。",
    "postIdea": "成片帧、角色控制结构、灰模、最终合成四格对比，文字只解释一个关键问题。",
    "adaptation": "把“可信环境 + 不可能动作 + 一眼可懂的幕后”迁移到自己的题材，不照搬作者角色或镜头。",
    "checkLabel": "原帖与播放画面已抽查",
    "nature": "个人作品 · 非 AI 使用证明",
    "url": "https://www.instagram.com/reel/Db8XbcuprRD/",
    "originalTitle": "MANIKANDAN RAJENDRAN on Instagram: \"Personal #blender project #breakdown \n.\n.\n.\n.\n.\n.\n.\n#cgi #vfx #animation\"",
    "originalPublishedAt": null,
    "image": "media/social/Db8XbcuprRD.jpg",
    "imageSource": "https://scontent-lax3-1.cdninstagram.com/v/t51.71878-15/774467462_960902417021039_4619497581277765360_n.jpg?stp=cmp1_dst-jpg_e35_s640x640_tt6&_nc_cat=108&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=AIB2VQxmcZEQ7kNvwFL2oTQ&_nc_oc=AdrF5jZQYZ1BpouzNQDKcxl6-JVWCm5QqwWECGJZUuGS8u25kid4vAV0yWir2ypXC40&_nc_zt=23&_nc_ht=scontent-lax3-1.cdninstagram.com&_nc_gid=Gz6ixASSSCRFyRiAF9Sbow&_nc_ss=7f60f&oh=00_AQKxrlNmcy9hWYaNZyu95O6DQWB7GAFq3Rwc0-Z01xf6jg&oe=6AA8418E",
    "snapshot": "research/2026-09-10/social/d2314887f3e5b7c358eaa6d21ae79163.json",
    "checkedAt": "2026-09-10T08:21:51+00:00",
    "collectedAt": "2026-09-10",
    "videoId": null
  },
  {
    "id": "253975615",
    "author": "Edwa Og",
    "platform": "Behance",
    "format": "视频＋图文",
    "use": "产品视觉",
    "publishedLabel": "2026-08-08（平台日期，未提供时区）",
    "title": "手表不是直接出现，而是从材料中逐步成形",
    "desc": "AKHOR 把液态金属、石材与晶体、机械组装和成品展示串成一条产品叙事，而不只是转一圈展示手表。",
    "combination": "产品 CG × 材料变形 × 机械组装",
    "tools": "作者列出 Houdini、Cinema 4D、Blender、Redshift、After Effects",
    "method": "项目正文按 MATERIAL、MECHANISM、STRUCTURE、WATCH 展开，明确结合程序化模拟、产品可视化和动态设计。",
    "evidence": "作者项目正文及 Tools 列表；页面各章节可按上述英文标题定位。",
    "unknown": "各软件具体承担的镜头、参数、预算及商业委托关系未公开核实；未宣称使用 AI。",
    "hook": "编辑观察：先看见材料，再理解它如何成为产品，比连续功能字幕更有视觉悬念。",
    "videoIdea": "给自有产品设计三段变化：材料聚合 → 结构成形 → 最终用途。不要照搬手表或品牌标识。",
    "postIdea": "材料板、结构分解、最终产品三页，给每页配一句创作选择。",
    "adaptation": "借鉴“从原料到成品”的组织方式。简化版可用静态模型、灯光变化和剪辑完成，不必直接上复杂模拟。",
    "checkLabel": "作者图文与工具列表已核实",
    "nature": "作者作品展示",
    "url": "https://www.behance.net/gallery/253975615/AKHOR-CGI-Watch-Film",
    "originalTitle": "AKHOR — CGI Watch Film - Edwa Og",
    "originalPublishedAt": null,
    "image": "media/social/253975615.png",
    "imageSource": "https://mir-s3-cdn-cf.behance.net/projects/max_808/ad874b253975615.Y3JvcCwxMzgwLDEwODAsMzExLDA.png",
    "snapshot": "research/2026-09-10/social/3d7b02ec0ed6f16bc9c44c884611c82c.json",
    "checkedAt": "2026-09-10T08:21:49+00:00",
    "collectedAt": "2026-09-10",
    "videoId": null
  },
  {
    "id": "uC8hzJvDHxs",
    "author": "MDMZ · Mohamed Mehrez",
    "platform": "YouTube",
    "format": "制作过程",
    "use": "AI 工作流",
    "title": "一张图到可动角色：把资产的下一步也拍出来",
    "desc": "作者把生成角色、分件、重新贴图、PBR 与动画串进同一条教程，展示模型生成之后还能继续做什么。",
    "combination": "AI 图像 / 3D × 材质调整 × 角色动画",
    "tools": "Tripo；简介列出 OpenArt、Mixamo",
    "method": "原视频章节：0:26 生成角色；3:01 分件；5:59 重新贴图；7:32 PBR；9:01 动画。工具来自作者简介，不代表已验证每个镜头的参数。",
    "evidence": "原视频简介与作者章节，可点击时间定位。",
    "unknown": "实际工时、成功率、是否补做人工修模未全面核实；简介披露 affiliate links，折扣码注明已失效。",
    "hook": "编辑观察：以同一个角色贯穿多个阶段，比罗列功能更容易建立“从无到有”的满足感。",
    "videoIdea": "做 30–45 秒的自有角色版本：参考图 → 模型 → 一次人工修改 → 动起来 → 实际用途。",
    "postIdea": "轮播封面展示最终角色，后续分别展示输入、结构、材质和动画，并写清失败或修正点。",
    "adaptation": "先确定最终用途，再决定展示哪些步骤；保留人工设计判断，不承诺一键获得成片。",
    "checkLabel": "原简介与章节已核实",
    "nature": "创作者教程 · 披露联盟推广",
    "chapters": [
      [
        "0:26 角色生成",
        26
      ],
      [
        "3:01 分件",
        181
      ],
      [
        "5:59 贴图",
        359
      ],
      [
        "9:01 动画",
        541
      ]
    ],
    "url": "https://www.youtube.com/watch?v=uC8hzJvDHxs",
    "originalTitle": "How To Turn an Image into a 3D Model | Tripo AI Tutorial",
    "originalPublishedAt": "2025-07-15T06:18:47-07:00",
    "publishedLabel": "2025-07-15 21:18（北京时间）",
    "image": "media/social/uC8hzJvDHxs.jpg",
    "imageSource": "https://i.ytimg.com/vi/uC8hzJvDHxs/maxresdefault.jpg",
    "snapshot": "research/2026-09-10/social/fb10e7c32d52594010c1972106d46ed1.json",
    "checkedAt": "2026-09-10T08:22:37+00:00",
    "collectedAt": "2026-09-10",
    "videoId": "uC8hzJvDHxs"
  },
  {
    "id": "EpdwqxSQMr0",
    "author": "Tilda",
    "platform": "YouTube",
    "format": "交互演示",
    "use": "交互体验",
    "title": "让观众动手：把 3D 动画放进可交互网页",
    "desc": "Tilda 官方公开视频示范在 Zero Block 与 Spline 中重建交互式 3D 动画；可借鉴的是把作品变成可操作体验的表达。",
    "combination": "3D 场景 × 网页交互 × 屏幕演示",
    "tools": "Tilda Zero Block + Spline（原简介确认）",
    "method": "作者说明用 Zero Block 与 Spline 重建一个交互 3D 动画；实际交互细节应以原片为准。",
    "evidence": "官方发布视频标题、封面、作者及完整简介。",
    "unknown": "未取得可独立操作的成品链接，当前收录的是交互演示视频，不是可在本站直接玩的项目；未核实用户留存提升。",
    "hook": "编辑建议：先演示一次操作与反馈，让观众马上知道“这个模型能做什么”。",
    "videoIdea": "录下鼠标操作与模型响应的同屏过程，再用一句话说明互动规则；不要只有模型空转。",
    "postIdea": "封面是交互结果；两页展示操作前后；末页放自己作品的可用链接或二维码。",
    "adaptation": "让自有模型响应一次点击或拖动，做成有明确反馈的小体验，再把屏幕演示剪成社媒内容。",
    "checkLabel": "官方视频简介已核实",
    "nature": "工具官方教程 · 交互演示",
    "url": "https://www.youtube.com/watch?v=EpdwqxSQMr0",
    "originalTitle": "How To Create an Interactive 3D Website (Tilda x Spline Tutorial)",
    "originalPublishedAt": "2026-04-10T06:46:54-07:00",
    "publishedLabel": "2026-04-10 21:46（北京时间）",
    "image": "media/social/EpdwqxSQMr0.jpg",
    "imageSource": "https://i.ytimg.com/vi/EpdwqxSQMr0/maxresdefault.jpg",
    "snapshot": "research/2026-09-10/social/e8ed207f9918120bb2ce016ef8561cd0.json",
    "checkedAt": "2026-09-10T08:23:10+00:00",
    "collectedAt": "2026-09-10",
    "videoId": "EpdwqxSQMr0"
  },
  {
    "id": "250350409",
    "author": "Dima Mnatsakanian",
    "platform": "Behance",
    "format": "视频＋图文",
    "use": "概念与设计",
    "publishedLabel": "2026-06-03（平台日期，未提供时区）",
    "title": "给虚构设备做一次“产品发布”：PX-01 概念设计",
    "desc": "作者以虚构投影设备为对象，结合工业设计、触觉交互概念与电影感产品可视化；封面用旋钮、材质和标识建立产品感。",
    "combination": "虚构产品 × 工业设计 × 发布视觉",
    "tools": "作者列出 Plasticity、Cinema 4D、Redshift、After Effects、Figma",
    "method": "作者明确说明 PX-01 是 fictional projection device，并以 Teenage Engineering 的功能极简风格为参考。工具表是项目级信息，非逐步操作记录。",
    "evidence": "原项目描述、Tools 和 Published；封面已检查。",
    "unknown": "没有实物量产或品牌委托证据；不能把概念设备介绍成在售产品。",
    "hook": "编辑观察：先给观众一个可信的设计细节，再揭示“这是我设计的虚构设备”。",
    "videoIdea": "用原创产品做假想发布，但在标题或字幕清楚标注概念设计；展示一个有趣的使用设定。",
    "postIdea": "产品主视觉 → 旋钮等细节 → 设计设定 → 草图/模型过程，形成一份可读的概念提案。",
    "adaptation": "选日常物件重新设定用途，用 3D 将概念可视化；借鉴组织方式，不复制现有品牌语言。",
    "checkLabel": "作者描述与封面已核实",
    "nature": "虚构概念 · 非量产产品",
    "url": "https://www.behance.net/gallery/250350409/PX-01-Visual-Playback-Device-Concept",
    "originalTitle": "PX-01 — Visual Playback Device Concept - Dima Mnatsakanian",
    "originalPublishedAt": null,
    "image": "media/social/250350409.png",
    "imageSource": "https://mir-s3-cdn-cf.behance.net/project_modules/1400/03f816250350409.6a2026c4e38a8.png",
    "snapshot": "research/2026-09-10/social/21c62b2a5a935171942fd1a45f34d5fc.json",
    "checkedAt": "2026-09-10T08:21:49+00:00",
    "collectedAt": "2026-09-10",
    "videoId": null
  },
  {
    "id": "HB03x_AQO4c",
    "author": "LightArchitect",
    "platform": "YouTube",
    "format": "制作过程",
    "use": "实拍与特效",
    "title": "一条战场镜头，拆成实拍、3D 和二维合成三层",
    "desc": "作者公开分解战场 VFX：数字替身、飞机、环境、爆炸等在 Blender 与 After Effects 中结合，展示画面各层分别做了什么。",
    "combination": "实拍 × CG 资产 × 二维素材合成",
    "tools": "Blender + Adobe After Effects（作者简介确认）",
    "method": "作者说明 Blender 负责建模、动画、模拟、材质、灯光与摄影机跟踪；After Effects 负责合成、素材元素、二维绘景扩景与调色。",
    "evidence": "原视频完整简介与封面；制作流程为作者自述，未独立复现。",
    "unknown": "未逐镜确认哪些爆炸来自模拟或素材库；不能把所有效果都说成 3D 模拟。原简介有插件推广。",
    "hook": "编辑建议：同一画面逐层增加元素，让观众看见每一层的作用。",
    "videoIdea": "缩小成一条安全、简单的实拍镜头：原片 → 加模型 → 加阴影/光照 → 最终合成。",
    "postIdea": "四格分层图，标出“实拍”“3D”“二维效果”“调色”，避免一长串术语。",
    "adaptation": "借鉴分层揭示法，把日常桌面或街景做出一个明显变化；不需要复刻战争题材。",
    "checkLabel": "作者流程说明已核实",
    "nature": "制作拆解 · 含插件推广",
    "url": "https://www.youtube.com/watch?v=HB03x_AQO4c",
    "originalTitle": "No AI Here! We Built a CGI Battlefield in Blender – Full VFX Breakdown ft. Chris Moss",
    "originalPublishedAt": "2026-06-02T11:24:52-07:00",
    "publishedLabel": "2026-06-03 02:24（北京时间）",
    "image": "media/social/HB03x_AQO4c.jpg",
    "imageSource": "https://i.ytimg.com/vi/HB03x_AQO4c/maxresdefault.jpg",
    "snapshot": "research/2026-09-10/social/37c0984ab3dfe45ff0b280a5fa2097d9.json",
    "checkedAt": "2026-09-10T08:20:59+00:00",
    "collectedAt": "2026-09-10",
    "videoId": "HB03x_AQO4c"
  },
  {
    "id": "252699273",
    "author": "Ilya Orlov",
    "platform": "Behance",
    "format": "图文",
    "use": "概念与设计",
    "publishedLabel": "2026-07-15（平台日期，未提供时区）",
    "title": "极简硬件系列：用材质与构图做持续更新的帖子",
    "desc": "Minimal Hardware Collection 是个人 CGI 探索系列，把工业设计物件放在统一的简洁视觉语言中，研究形态、材料、灯光和构图。",
    "combination": "工业设计 × CGI 静帧 / 动图 × 系列化表达",
    "tools": "Cinema 4D + Octane Render + After Effects（作者正文确认）",
    "method": "作者称这是持续进行的个人探索系列，公开说明了软件组合与形态、材料、灯光、构图四个关注点。原页面含动图，本站封面用其首帧。",
    "evidence": "原项目正文、发布时间、工具列表和原始封面。",
    "unknown": "未公开完整节点、灯光参数或每件作品的工时；无品牌订单证明。",
    "hook": "编辑观察：统一排版和灯光，让不同作品形成可以连续追看的系列。",
    "videoIdea": "固定机位，只改变一种材料或一种功能细节，做 3–5 个短版本供观众比较。",
    "postIdea": "一组 4–6 张统一构图的材质实验，每张只解释一个设计变量。",
    "adaptation": "从一个自有模型开始，做“同一物件的不同设计选择”，比每天重做复杂场景更容易持续。",
    "checkLabel": "作者图文与软件说明已核实",
    "nature": "个人 CGI 系列",
    "url": "https://www.behance.net/gallery/252699273/Minimal-Hardware-Collection",
    "originalTitle": "Minimal Hardware Collection - Ilya Orlov",
    "originalPublishedAt": null,
    "image": "media/social/252699273.jpg",
    "imageSource": "https://mir-s3-cdn-cf.behance.net/project_modules/1400/c1cb23252699273.6a578d40bc7c3.gif",
    "snapshot": "research/2026-09-10/social/cd74bbac88b2e97ccb2a59e6d834b0bf.json",
    "checkedAt": "2026-09-10T08:21:49+00:00",
    "collectedAt": "2026-09-10",
    "videoId": null
  },
  {
    "id": "249990577",
    "author": "Márcio Samuel Souza / Guilherme Salvia / By MOVIE",
    "platform": "Behance",
    "format": "视频＋图文",
    "use": "产品视觉",
    "publishedLabel": "2026-05-26（平台日期，未提供时区）",
    "title": "香水的气质怎么变成画面？从碳纤维意象出发",
    "desc": "作者的 Prada Luna Rossa Carbon 个人 CGI 练习，把瓶身材质、明暗对比与氛围结合，并发布风格帧和制作过程。",
    "combination": "香水产品 × 材料意象 × 风格帧",
    "tools": "项目列出 Cinema 4D、Redshift、3ds Max、Phoenix FD、Adobe 工具",
    "method": "正文明确称 personal CGI project，内容包括产品建模、灯光、lookdev 与渲染；页面分为 Study of Styleframes、Process。",
    "evidence": "原项目 About、风格帧、Process、Credits 与 Tools；原图封面可查看。",
    "unknown": "虽然页面出现 Client: Prada，但同时明确标 Study / personal；本库按个人练习处理，不认定为品牌委托。",
    "hook": "编辑建议：把抽象的“高级、冷感、力量”翻译成具体材质和光影，而不是堆形容词。",
    "videoIdea": "为自有产品选一个材料关键词，做材质细节 → 产品局部 → 主视觉的短片。",
    "postIdea": "情绪板 → 三张风格帧 → 最终主视觉，每页解释一个视觉选择。",
    "adaptation": "先写一句产品感受，再限定材料、配色和灯光三项规则；不要直接使用原品牌包装做商业发布。",
    "checkLabel": "个人练习属性已核实",
    "nature": "个人练习 · 非品牌委托证明",
    "url": "https://www.behance.net/gallery/249990577/PRADA-Luna-Rossa-3D-CGIProduct-Animation",
    "originalTitle": "PRADA Luna Rossa - 3D CGI/Product Animation",
    "originalPublishedAt": null,
    "image": "media/social/249990577.png",
    "imageSource": "https://mir-s3-cdn-cf.behance.net/project_modules/1400/fca552249990577.6a1842aa90db6.png",
    "snapshot": "research/2026-09-10/social/dc4eeebbbc54041c19c33c8d1fe9ab2e.json",
    "checkedAt": "2026-09-10T08:21:49+00:00",
    "collectedAt": "2026-09-10",
    "videoId": null
  },
  {
    "id": "DQliQlzE8kj",
    "author": "Lawson Cross · @lawson_cross",
    "platform": "Instagram",
    "format": "短视频",
    "use": "实拍与特效",
    "publishedLabel": "2025-11-02（原帖元数据）；浏览器显示 11-03，时区未核实",
    "title": "把幕后也做成内容：CGI 成片之后再发一条拆解",
    "desc": "作者为自己的剪辑单独发布 CGI / Blender breakdown；实际播放抽查可见 Blender 场景，让作品本身和制作过程分别成为内容。",
    "combination": "CGI 创作 × Blender 场景 × 幕后短视频",
    "tools": "Blender（正文明确）；其他软件未核实",
    "method": "原帖明确说明这是最新剪辑的 CGI 和 Blender 拆解。抽查画面能看到 Blender 场景与素材操作。",
    "evidence": "原帖正文、原始日期元数据与实际播放片段；日期跨日差异已保留。",
    "unknown": "没有核实完整动作捕捉方案、全部工具或工时；评论问到 mocap 不代表作者确认使用某软件。",
    "hook": "编辑建议：观众看完成片后最想知道的一个问题，就是幕后内容的标题。",
    "videoIdea": "同一个原创作品发两条：第一条展示结果，第二条只回答一个关键制作问题，保持画面对照。",
    "postIdea": "成片帧与 Blender 视口并排，再补三点“哪些是模型、哪些是贴图、哪些是合成”。",
    "adaptation": "把制作时已经有的视口和中间状态保留下来，不必为第二条内容重新创作全部资产。",
    "checkLabel": "原帖与播放画面已抽查",
    "nature": "创作者幕后拆解",
    "url": "https://www.instagram.com/reel/DQliQlzE8kj/",
    "originalTitle": "Lawson Cross on Instagram: \"Here the CGI and blender breakdown of how I made my latest edit 😎 #vfx #cgi #blender #behindthescenes #vfxbreakdown #tutorial #edit\"",
    "originalPublishedAt": null,
    "image": "media/social/DQliQlzE8kj.jpg",
    "imageSource": "https://scontent-lax7-1.cdninstagram.com/v/t51.71878-15/572959221_1369447951283578_9126758589678640929_n.jpg?stp=cmp1_dst-jpg_e35_s640x640_tt6&_nc_cat=101&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=hDmmCTBk9rAQ7kNvwFDMIcf&_nc_oc=AdqGR6PmAjeB3foATmVYTGahCWjFLf0a8t5_esH47ODyXrrLThs0P1vbmbrOhEgnssE&_nc_zt=23&_nc_ht=scontent-lax7-1.cdninstagram.com&_nc_gid=xjV14pVtctUa_m1JpEUUfQ&_nc_ss=7f60f&oh=00_AQIubefQSP9eo-lry5XbXeGT7V0PeRX7cfy4B_5hz7dhIg&oe=6AA855EF",
    "snapshot": "research/2026-09-10/social/641363dccafe33be1026bdde86a1ce8b.json",
    "checkedAt": "2026-09-10T08:20:59+00:00",
    "collectedAt": "2026-09-10",
    "videoId": null
  }
];
if(typeof module !== "undefined") module.exports=socialCases;
